import type { CharacterParams, ParamConfig, CharacterParamKey, ColorParamKey } from './types';

export const INITIAL_PARAMS: CharacterParams = {
  headWidth: 95,
  headHeight: 110,
  headShape: 'ellipse',
  headCornerRadius: 20,
  triangleCornerRadius: 10,
  eyeSizeRatio: 18,
  eyeSpacingRatio: 25,
  pupilSizeRatio: 50,
  upperEyelidCoverage: 18,
  lowerEyelidCoverage: 0,
  eyeStyle: 'blocky',
  eyeTracking: true,
  eyelashes: false,
  eyelashCount: 4,
  eyelashLength: 8,
  eyelashAngle: 25,
  glint: true,
  glintSizeRatio: 20,
  glintXOffsetRatio: 30,
  glintYOffsetRatio: -30,
  glintOpacity: 100,
  mouthWidthRatio: 50,
  mouthYOffsetRatio: 45,
  mouthBend: 25,
  eyebrows: true,
  eyebrowWidthRatio: 25,
  eyebrowHeightRatio: 40,
  eyebrowYOffsetRatio: 25,
  eyebrowAngle: -15,
  neckHeight: 20,
  neckWidthRatio: 40,
  torsoHeight: 140,
  torsoWidth: 140,
  torsoShape: 'circle',
  torsoCornerRadius: 20,
  pelvisHeight: 30,
  pelvisWidthRatio: 80,
  pelvisShape: 'rectangle',
  armLength: 112,
  lArmWidth: 11,
  rArmWidth: 11,
  lHandSize: 40,
  rHandSize: 40,
  legLength: 178,
  lLegWidth: 18,
  rLegWidth: 18,
  lFootSize: 35,
  rFootSize: 35,
  lArmAngle: 25,
  rArmAngle: 25,
  lArmBend: 30,
  rArmBend: -30,
  lLegAngle: 8,
  rLegAngle: 8,
  lLegBend: 0,
  rLegBend: 0,
  hair: true,
  backHairWidthRatio: 200,
  backHairHeightRatio: 100,
  backHairShape: 'smooth',
  hairCurliness: 0,
  hairCurlFrequency: 10,
  hairCurlAmplitude: 10,
  fringeHeightRatio: 30,
  viewAngle: 0,
  bodyColor: '#E97356',
  irisColor: '#4A2E2C',
  outlineColor: '#4A2E2C',
  pupilColor: '#4A2E2C',
  hairColor: '#4A2E2C',
  bodyOutlines: true,
  eyeOutlines: true,
};

export const PARAM_CONFIGS: Record<Exclude<CharacterParamKey, 'bodyOutlines' | 'eyeOutlines' | 'eyeStyle' | 'bodyColor' | 'irisColor' | 'outlineColor' | 'pupilColor' | 'headShape' | 'torsoShape' | 'eyeTracking' | 'pelvisShape' | 'eyelashes' | 'hair' | 'hairColor' | 'eyebrows' | 'glint' | 'backHairShape'>, ParamConfig> = {
  // Head
  headWidth: { min: 50, max: 130, step: 1, label: 'Head Width' },
  headHeight: { min: 70, max: 150, step: 1, label: 'Head Height' },
  headCornerRadius: { min: 0, max: 65, step: 1, label: 'Head Corners' },
  triangleCornerRadius: { min: 0, max: 50, step: 1, label: 'Triangle Corners' },
  backHairWidthRatio: { min: 200, max: 400, step: 1, label: 'Back Hair Width' },
  backHairHeightRatio: { min: 100, max: 150, step: 1, label: 'Back Hair Height' },
  hairCurliness: { min: 0, max: 100, step: 1, label: 'Hair Curliness' },
  hairCurlFrequency: { min: 1, max: 50, step: 1, label: 'Curl Frequency' },
  hairCurlAmplitude: { min: 0, max: 50, step: 1, label: 'Curl Amplitude' },
  fringeHeightRatio: { min: 0, max: 100, step: 1, label: 'Fringe Height' },
  eyeSizeRatio: { min: 8, max: 25, step: 1, label: 'Eye Size' },
  eyeSpacingRatio: { min: 15, max: 45, step: 1, label: 'Eye Spacing' },
  pupilSizeRatio: { min: 20, max: 70, step: 1, label: 'Pupil Size' },
  // FIX: Corrected typo from upperEylidCoverage to upperEyelidCoverage
  upperEyelidCoverage: { min: 0, max: 50, step: 1, label: 'Upper Eyelid' },
  // FIX: Corrected typo from lowerEylidCoverage to lowerEyelidCoverage
  lowerEyelidCoverage: { min: 0, max: 50, step: 1, label: 'Lower Eyelid' },
  eyelashCount: { min: 2, max: 8, step: 1, label: 'Eyelash Count' },
  eyelashLength: { min: 5, max: 25, step: 1, label: 'Eyelash Length' },
  eyelashAngle: { min: -30, max: 60, step: 1, label: 'Eyelash Angle' },
  glintSizeRatio: { min: 5, max: 50, step: 1, label: 'Glint Size' },
  glintXOffsetRatio: { min: -100, max: 100, step: 1, label: 'Glint X Offset' },
  glintYOffsetRatio: { min: -100, max: 100, step: 1, label: 'Glint Y Offset' },
  glintOpacity: { min: 0, max: 100, step: 1, label: 'Glint Opacity' },
  mouthWidthRatio: { min: 20, max: 70, step: 1, label: 'Mouth Width' },
  mouthYOffsetRatio: { min: 20, max: 80, step: 1, label: 'Mouth Position' },
  mouthBend: { min: -100, max: 100, step: 1, label: 'Mouth Bend' },
  eyebrowWidthRatio: { min: 15, max: 40, step: 1, label: 'Eyebrow Width' },
  eyebrowHeightRatio: { min: 20, max: 60, step: 1, label: 'Eyebrow Height' },
  eyebrowYOffsetRatio: { min: 10, max: 35, step: 1, label: 'Eyebrow Position' },
  eyebrowAngle: { min: -45, max: 45, step: 1, label: 'Eyebrow Angle' },
  viewAngle: { min: -90, max: 90, step: 1, label: 'Ángulo de Vista' },
  
  // Body
  neckHeight: { min: 10, max: 50, step: 1, label: 'Neck Height' },
  neckWidthRatio: { min: 30, max: 50, step: 1, label: 'Neck Width Ratio' },
  torsoHeight: { min: 80, max: 220, step: 1, label: 'Torso Height' },
  torsoWidth: { min: 60, max: 180, step: 1, label: 'Torso Width' },
  torsoCornerRadius: { min: 0, max: 90, step: 1, label: 'Torso Corners' },
  pelvisHeight: { min: 10, max: 60, step: 1, label: 'Pelvis Height' },
  pelvisWidthRatio: { min: 50, max: 110, step: 1, label: 'Pelvis Width Ratio' },

  // Arms
  armLength: { min: 50, max: 180, step: 1, label: 'Arm Length' },
  lArmWidth: { min: 8, max: 40, step: 1, label: 'L Arm Width' },
  rArmWidth: { min: 8, max: 40, step: 1, label: 'R Arm Width' },
  lHandSize: { min: 10, max: 40, step: 1, label: 'L Hand Size' },
  rHandSize: { min: 10, max: 40, step: 1, label: 'R Hand Size' },
  lArmAngle: { min: -90, max: 120, step: 1, label: 'L Arm Angle' },
  lArmBend: { min: -150, max: 150, step: 1, label: 'L Arm Bend' },
  rArmAngle: { min: -90, max: 120, step: 1, label: 'R Arm Angle' },
  rArmBend: { min: -150, max: 150, step: 1, label: 'R Arm Bend' },

  // Legs
  legLength: { min: 60, max: 200, step: 1, label: 'Leg Length' },
  lLegWidth: { min: 10, max: 50, step: 1, label: 'L Leg Width' },
  rLegWidth: { min: 10, max: 50, step: 1, label: 'R Leg Width' },
  lFootSize: { min: 15, max: 50, step: 1, label: 'L Foot Size' },
  rFootSize: { min: 15, max: 50, step: 1, label: 'R Foot Size' },
  lLegAngle: { min: -45, max: 45, step: 1, label: 'L Leg Angle' },
  lLegBend: { min: -150, max: 150, step: 1, label: 'L Leg Bend' },
  rLegAngle: { min: -45, max: 45, step: 1, label: 'R Leg Angle' },
  rLegBend: { min: -150, max: 150, step: 1, label: 'R Leg Bend' },
};


export const COUNTRIES = [
  { name: 'Global', code: 'GLOBAL' },
  { name: 'Argentina', code: 'AR' },
  { name: 'Australia', code: 'AU' },
  { name: 'Brazil', code: 'BR' },
  { name: 'Canada', code: 'CA' },
  { name: 'Chile', code: 'CL' },
  { name: 'France', code: 'FR' },
  { name: 'Germany', code: 'DE' },
  { name: 'India', code: 'IN' },
  { name: 'Indonesia', code: 'ID' },
  { name: 'Italy', code: 'IT' },
  { name: 'Japan', code: 'JP' },
  { name: 'Mexico', code: 'MX' },
  { name: 'Netherlands', code: 'NL' },
  { name: 'Nigeria', code: 'NG' },
  { name: 'Poland', code: 'PL' },
  { name: 'Russia', code: 'RU' },
  { name: 'Saudi Arabia', code: 'SA' },
  { name: 'South Africa', code: 'ZA' },
  { name: 'South Korea', code: 'KR' },
  { name: 'Spain', code: 'ES' },
  { name: 'Sweden', code: 'SE' },
  { name: 'Turkey', code: 'TR' },
  { name: 'United Kingdom', code: 'GB' },
  { name: 'United States', code: 'US' },
];